/**
 * Shared helpers for the image-input sessions (MULTIMODAL_INPUT_IMPLEMENTATION.md
 * S01 onward). Three jobs, all trivial on purpose:
 *
 *  1. Point tests at the committed fixtures in `test/fixtures/images/` and read
 *     their bytes. Those files are real encoded images of a few KB each
 *     (regenerated by `scripts/make-image-fixtures.mjs`); over-limit inputs are
 *     synthesized in the tests that need them, never committed.
 *  2. Build `ImageAttachmentRef` values. The interface is copied from the
 *     design doc §5.1; S02 moves the canonical declaration to
 *     `src/media/types.ts`, and this helper should then import it from there
 *     instead of keeping its own copy.
 *  3. Assert that a provider payload (or any JSON-ish structure) carries no
 *     raw image bytes — the "log redaction" invariant S19 enforces for real.
 *     The walk recognizes both wire shapes the payload modules emit
 *     (Anthropic `source: { type: 'base64', data }`, OpenAI
 *     `image_url: { url: 'data:image/…;base64,…' }`) plus any long
 *     base64-alphabet string, so a regression cannot hide behind "it was in a
 *     different field".
 */
import assert from 'node:assert/strict'
import { statSync } from 'node:fs'
import { mkdir, mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const fixtureDir = path.join(
  path.dirname(path.dirname(fileURLToPath(import.meta.url))),
  'fixtures',
  'images',
)

/**
 * Design doc §5.1. Metadata beyond this shape (original MIME, EXIF orientation,
 * digests, processing version) lives in the attachment store, not in messages.
 * Kept here until S02 lands `src/media/types.ts`.
 */
export interface ImageAttachmentRef {
  id: string
  ownerSessionId: string
  name: string
  mimeType: 'image/png' | 'image/jpeg' | 'image/webp'
  width: number
  height: number
  byteLength: number
}

/** Absolute path of a committed image fixture; `name` must exist there. */
export function fixtureImagePath(name: string): string {
  return path.join(fixtureDir, name)
}

/** Bytes of a committed image fixture. */
export function loadFixtureBytes(name: string): Promise<Buffer> {
  return readFile(fixtureImagePath(name))
}

/**
 * Read off disk rather than written down: the default ref describes
 * `transparent.png`, so a hardcoded size would drift the first time a
 * libvips/sharp upgrade re-encodes the fixture, and the failure would land in
 * whichever store round-trip test compares written bytes against `byteLength`.
 */
const transparentPngByteLength = statSync(fixtureImagePath('transparent.png')).size

/** Build an `ImageAttachmentRef`; unknown fields stay at the documented defaults. */
export function makeImageAttachmentRef(
  overrides: Partial<ImageAttachmentRef> = {},
): ImageAttachmentRef {
  return {
    id: 'img-test-1',
    ownerSessionId: 'session-test',
    name: 'transparent.png',
    mimeType: 'image/png',
    width: 64,
    height: 64,
    byteLength: transparentPngByteLength,
    ...overrides,
  }
}

export interface TempAttachmentArea {
  /** Temp root standing in for a project's `<cwd>/.myagent` directory. */
  readonly root: string
  /** `<root>/attachments/<sessionId>`, already created (S05 storage layout). */
  readonly attachmentsDir: string
  readonly sessionId: string
  /** Remove the whole temp root. Safe to call more than once. */
  readonly cleanup: () => Promise<void>
}

/**
 * Create a temp attachment directory shaped like the S05 store:
 * `<root>/attachments/<sessionId>/`, ready for `<imageId>/original.<ext>` etc.
 * `cleanup` removes the entire root, not just the session directory.
 */
export async function createTempAttachmentArea(
  sessionId = 'session-test',
): Promise<TempAttachmentArea> {
  const root = await mkdtemp(path.join(tmpdir(), 'hanekawa-attachments-'))
  const attachmentsDir = path.join(root, 'attachments', sessionId)
  await mkdir(attachmentsDir, { recursive: true })
  let cleaned = false
  return {
    root,
    attachmentsDir,
    sessionId,
    cleanup: async () => {
      if (cleaned) return
      cleaned = true
      await rm(root, { recursive: true, force: true })
    },
  }
}

/** Strings that begin like an image data URL, e.g. `data:image/png;base64,…`. */
const DATA_URL_IMAGE = /^data:image\/[a-z0-9.+-]+;base64,/i
/** A run of ≥256 base64-alphabet characters — not proof, but nothing legit in
 *  a text payload looks like this, and redacted payloads never contain it. */
const BASE64_RUN = /^[A-Za-z0-9+/=\r\n]{256,}$/

/** A binary blob this size or larger is image bytes, not an incidental field. */
const MAX_INCIDENTAL_BINARY_BYTES = 64

/**
 * Assert that no raw image bytes survive anywhere inside `value`.
 *
 * Fails on: image data URLs, `{ type: 'base64', data: <raw> }` blocks (the
 * Anthropic wire shape — `data` must be absent or a `[redacted…]` marker), any
 * standalone base64-sized string, and any `Buffer`/typed array/`ArrayBuffer` of
 * real length — that last one being the *pre-serialization* shape a redaction
 * regression takes, before anything has had a chance to base64 it. Cycles are
 * tolerated (each object is visited once).
 */
export function assertNoImageBytes(value: unknown, label = 'payload'): void {
  const seen = new Set<unknown>()
  const walk = (node: unknown, pathLabel: string): void => {
    if (ArrayBuffer.isView(node) || node instanceof ArrayBuffer) {
      // Checked before the recursion below, which would otherwise enumerate a
      // typed array's integer indices — one `walk` frame per byte.
      assert.ok(
        node.byteLength < MAX_INCIDENTAL_BINARY_BYTES,
        `${pathLabel}: ${node.byteLength} raw bytes survived redaction as ${node.constructor.name}`,
      )
      return
    }
    if (node === null || typeof node !== 'object') {
      if (typeof node === 'string') {
        assert.ok(
          !DATA_URL_IMAGE.test(node),
          `${pathLabel}: image data URL survived redaction`,
        )
        assert.ok(
          !BASE64_RUN.test(node),
          `${pathLabel}: ${node.length}-character base64 run survived redaction`,
        )
      }
      return
    }
    if (seen.has(node)) return
    seen.add(node)
    if (Array.isArray(node)) {
      node.forEach((item, index) => walk(item, `${pathLabel}[${index}]`))
      return
    }
    const record = node as Record<string, unknown>
    if (record['type'] === 'base64') {
      const data = record['data']
      if (typeof data === 'string' && !data.startsWith('[redacted')) {
        assert.fail(
          `${pathLabel}: base64 source block carries ${data.length} raw data characters`,
        )
      }
    }
    for (const [key, child] of Object.entries(record)) {
      walk(child, `${pathLabel}.${key}`)
    }
  }
  walk(value, label)
}
